### ISSUE TITLE
RaftCluster start implementation on platforms other than mac incomplete

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/digital_me#33]
needs completing.

**Comment by delandtj** [comment]
```
======================================================================
ERROR: test0038_j_servers_raftserver_test (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/core9/tests/jumpscale_test/test09_js_dynamic_walker.py", line 139, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/digital_me/DigitalMeLib/servers/raft/RaftServerFactory.py", line 49, in test
    self.start_local(nrservers=4,startport=6000,cmd="j.servers.raftserver.example_server_class_get()")
  File "/opt/code/github/threefoldtech/digital_me/DigitalMeLib/servers/raft/RaftServerFactory.py", line 42, in start_local
    cluster.start(background=True)
  File "/opt/code/github/threefoldtech/digital_me/DigitalMeLib/servers/raft/RaftCluster.py", line 55, in start
    raise Exception("issue #33 - implement to find local ipaddr and "
Exception: issue #33 - implement to find local ipaddr and then based on own addr decide to start locally or not

======================================================================
ERROR: test0039_j_servers_raftserver_test_nopasswd (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/core9/tests/jumpscale_test/test09_js_dynamic_walker.py", line 139, in _testfn
    newobj()
  File "/opt/code/github/threefoldtech/digital_me/DigitalMeLib/servers/raft/RaftServerFactory.py", line 55, in test_nopasswd
    self.start_local(nrservers=4,startport=6000,cmd="j.servers.raftserver.example_server_class_get()",secret="")
  File "/opt/code/github/threefoldtech/digital_me/DigitalMeLib/servers/raft/RaftServerFactory.py", line 42, in start_local
    cluster.start(background=True)
  File "/opt/code/github/threefoldtech/digital_me/DigitalMeLib/servers/raft/RaftCluster.py", line 55, in start
    raise Exception("issue #33 - implement to find local ipaddr and "
Exception: issue #33 - implement to find local ipaddr and then based on own addr decide to start locally or not
```

disabling dynamic unit-test walking for now

**Comment by delandtj** [comment]
commit 5558170 in core
