### ISSUE TITLE
j.servers.web failing (NameError 'app' is not defined')

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/digital_me#39]
```
======================================================================
ERROR: test  26_j_servers_web_error (tests.jumpscale_test.test09_js_dynamic_walker.TestJSDynamicWalkerTestSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lkcl/src/core9/tests/jumpscale_test/test09_js_dynamic_walker.py", line 119, in _testfn
    raise e
  File "/home/lkcl/src/core9/tests/jumpscale_test/test09_js_dynamic_walker.py", line 75, in compare
    subobj1 = getattr(obj1, subname)
  File "/home/lkcl/src/core9/Jumpscale/core/JSBase.py", line 426, in __getattribute__
    instance = d[name].getter()
  File "/home/lkcl/src/core9/Jumpscale/core/JSBase.py", line 526, in getter
    return self.obj
  File "/home/lkcl/src/core9/Jumpscale/core/JSBase.py", line 532, in obj
    self._obj = self.kls()
  File "/home/lkcl/src/core9/Jumpscale/core/JSBase.py", line 502, in kls
    kls = lookup_kls(self.fullpath, self.modulepath, _kls)
  File "/home/lkcl/src/core9/Jumpscale/core/JSBase.py", line 136, in lookup_kls
    module = jspath_import(mpathname, fullpath)
  File "/home/lkcl/src/core9/Jumpscale/core/JSBase.py", line 72, in jspath_import
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/servers/webserver/JSWebServers.py", line 2, in <module>
    from .JSWebServer import JSWebServer
  File "/home/lkcl/src/lib9/JumpscaleLib/servers/webserver/JSWebServer.py", line 20, in <module>
    class JSWebServer(JSConfigBase):
  File "/home/lkcl/src/lib9/JumpscaleLib/servers/webserver/JSWebServer.py", line 43, in JSWebServer
    def register_blueprints(self,app=app):
NameError: name 'app' is not defined
```

related to lib issue https://github.com/threefoldtech/jumpscale_lib/issues/105

**Comment by delandtj** [comment]
commit core9  2b86da1
