### ISSUE TITLE
missing peewee package

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digital_me#44]
branch: development_simple

```
Traceback (most recent call last):
  File "/usr/local/bin/js_shell", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/threefoldtech/jumpscale_core/cmds/js_shell", line 34, in <module>
    exec(toexec)
  File "<string>", line 1, in <module>
  File "/tmp/jumpscale/jumpscale_generated.py", line 2437, in bcdb
    msg = j.core.application.error_init("import", "DigitalMeLib.data.bcdb.BCDBFactory", e)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/core/Application.py", line 66, in error_init
    raise RuntimeError(msg)
RuntimeError: import:DigitalMeLib.data.bcdb.BCDBFactory:No module named 'peewee'
```

**Comment by siddiquagig** [comment]
On a fresh install of development_960 or development_simple  its still not installed along with other packages also:

```
Collecting Cython
  Downloading https://files.pythonhosted.org/packages/64/3f/cac281f3f019b825bbc03fa8cb7eb03d9c355f4aa9eef978279a4966cb21/Cython-0.29-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 4.6MB/s
Installing collected packages: Cython
Successfully installed Cython-0.29
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/ff/7f/9d804d2348471c67a7d8b5f84f9bc59fd1cefa148986f2b74552f8573555/numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 1.7MB/s
Installing collected packages: numpy
Successfully installed numpy-1.15.4
Collecting PyNaCl
  Downloading https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759kB)
    100% |████████████████████████████████| 768kB 5.0MB/s
Requirement already satisfied, skipping upgrade: cffi>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from PyNaCl) (1.11.5)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from PyNaCl) (1.11.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.4.1->PyNaCl) (2.19)
jumpscalelib 9.5.1 requires blosc>=1.5.1, which is not installed.
jumpscalelib 9.5.1 requires Brotli>=0.6.0, which is not installed.
jumpscalelib 9.5.1 requires cson>=0.7, which is not installed.
jumpscalelib 9.5.1 requires docker>=2.2.1, which is not installed.
jumpscalelib 9.5.1 requires ed25519>=1.4, which is not installed.
jumpscalelib 9.5.1 requires etcd3>=0.7.0, which is not installed.
jumpscalelib 9.5.1 requires grequests>=0.3.0, which is not installed.
jumpscalelib 9.5.1 requires influxdb>=4.1.0, which is not installed.
jumpscalelib 9.5.1 requires ipcalc>=1.99.0, which is not installed.
jumpscalelib 9.5.1 requires netifaces>=0.10.5, which is not installed.
jumpscalelib 9.5.1 requires ovh>=0.4.7, which is not installed.
jumpscalelib 9.5.1 requires packet-python>=1.37, which is not installed.
**jumpscalelib** 9.5.1 requires peewee>=2.9.2, which is not installed**
jumpscalelib 9.5.1 requires psycopg2>=2.6.2, which is not installed.
jumpscalelib 9.5.1 requires pudb>=2017.1.2, which is not installed.
jumpscalelib 9.5.1 requires pyblake2>=0.9.3, which is not installed.
jumpscalelib 9.5.1 requires pycapnp>=0.5.12, which is not installed.
jumpscalelib 9.5.1 requires PyGithub>=1.34, which is not installed.
jumpscalelib 9.5.1 requires pymux>=0.13, which is not installed.
jumpscalelib 9.5.1 requires pyOpenSSL>=17.0.0, which is not installed.
jumpscalelib 9.5.1 requires python-jose>=1.3.2, which is not installed.
jumpscalelib 9.5.1 requires SQLAlchemy>=1.1.9, which is not installed.
jumpscalelib 9.5.1 requires uvloop>=0.8.0, which is not installed.
jumpscalelib 9.5.1 requires zerotier>=1.1.2, which is not installed.
jumpscalelib 9.5.1 has requirement cryptography>=2.2.0, but you'll have cryptography 2.1.4 which is incompatible.
Installing collected packages: PyNaCl
  Found existing installation: PyNaCl 1.1.2
    Uninstalling PyNaCl-1.1.2:
      Successfully uninstalled PyNaCl-1.1.2
Successfully installed PyNaCl-1.3.0
[+] jumpscale installed (OK)
```

**Comment by ahmadnazih** [comment]
i didn't put the peewee package in the dependencies i actually deleted the import line in the code as the import wasn't used
